version: '3'

services:
  db:
    container_name: mariadb
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=P@ssw0rd
      - MYSQL_DATABASE=spring_guide
      - MYSQL_USER=spring_guide
      - MYSQL_PASSWORD=P@ssw0rd
    restart: always
    ports:
      - 3306:3306
    volumes:
      - mariadb:/var/lib/mysql
  api:
    container_name: api
    build: .
    # image: spring-guide-img
    # build:
      # context: ./
      # dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - 8080:8080
    restart: always   

volumes:
  mariadb: